In [3]:
# import numpy 
import numpy as np

In [1]:
# create tensor based on 32 elements vector 

# Importing the necessary library
import torch

# Creating a 32-elements vector
vector = list(range(32))

# Converting the list into a tensor
tensor = torch.tensor(vector)

# Now let's print the tensor and verify our results
print(tensor)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])


To jest pierwszy **notebook** oparty o mechanizm <span style="color:red; font-weight:bold; font-size:18pt">Jupyter Notebook</span>.
<p><img src="gwiazda.jpg" width=400></p>

In [4]:
w = np.array([[1,2,3,4],[9,10,11,14],[35,36,37,40]])
w

array([[ 1, 2, 3, 4],
 [ 9, 10, 11, 14],
 [35, 36, 37, 40]])

In [5]:
w[w<5]

array([1, 2, 3, 4])

In [6]:
pc = (w>5)
w[pc]

array([ 9, 10, 11, 14, 35, 36, 37, 40])

In [7]:
logw = (w%2==0)
w[logw]

array([ 2, 4, 10, 14, 36, 40])

In [8]:
cv = w[(w>2) & (w<=21)]
cv

array([ 3, 4, 9, 10, 11, 14])

In [11]:
sv = w[(w<8) | (w>=35)]
sv

array([ 1, 2, 3, 4, 35, 36, 37, 40])