In [1]:
# import numpy 
import numpy as np

In [2]:
# create tensor based on 32 elements vector 

# Importing the necessary library
import torch

# Creating a 32-elements vector
vector = list(range(32))

# Converting the list into a tensor
tensor = torch.tensor(vector)

# Now let's print the tensor and verify our results
print(tensor)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])


To jest pierwszy **notebook** oparty o mechanizm <span style="color:red; font-weight:bold; font-size:18pt">Jupyter Notebook</span>.
<p><img src="gwiazda.jpg" width=400></p>

In [3]:
w = np.array([[1,2,3,4],[9,10,11,14],[35,36,37,40]])
w

array([[ 1, 2, 3, 4],
 [ 9, 10, 11, 14],
 [35, 36, 37, 40]])

In [4]:
w[w<5]

array([1, 2, 3, 4])

In [5]:
pc = (w>5)
w[pc]

array([ 9, 10, 11, 14, 35, 36, 37, 40])

In [6]:
logw = (w%2==0)
w[logw]

array([ 2, 4, 10, 14, 36, 40])

In [7]:
cv = w[(w>2) & (w<=21)]
cv

array([ 3, 4, 9, 10, 11, 14])

In [8]:
sv = w[(w<8) | (w>=35)]
sv

array([ 1, 2, 3, 4, 35, 36, 37, 40])

In [9]:
dane = np.array([1,3,8])
one = np.ones(3,dtype=int)
tw = np.array([2,2,3])

In [10]:
print(dane+one)

[2 4 9]


In [11]:
print(dane-one)

[0 2 7]


In [12]:
print(dane*tw)

[ 2  6 24]


In [13]:
print(dane/tw)

[0.5        1.5        2.66666667]


In [14]:
print(dane*1.88)

[ 1.88  5.64 15.04]


In [15]:
m1 = np.array([[4,8,11],[67,101,3],[1,1,77]])
m2 = np.array([[488,9,3],[23,89,3],[2,4,11]])

wynik = (m1+m2)*m1
wynik

array([[ 1968, 136, 154],
 [ 6030, 19190, 18],
 [ 3, 5, 6776]])

In [17]:
print(f'wartość minimum: {wynik.min()}')
print(f'wartość maksimum: {wynik.max()}')
print(f'wartość średnia: {wynik.mean()}')
print(f'wartość std: {wynik.std()}')

wartość minimum: 3
wartość maksimum: 19190
wartość średnia: 3808.8888888888887
wartość std: 5998.870809381906


In [18]:
#tensor
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [19]:
#tablica 5D

arr5 = np.arange(240).reshape((2,2,4,5,3))
arr5

array([[[[[  0,   1,   2],
          [  3,   4,   5],
          [  6,   7,   8],
          [  9,  10,  11],
          [ 12,  13,  14]],

         [[ 15,  16,  17],
          [ 18,  19,  20],
          [ 21,  22,  23],
          [ 24,  25,  26],
          [ 27,  28,  29]],

         [[ 30,  31,  32],
          [ 33,  34,  35],
          [ 36,  37,  38],
          [ 39,  40,  41],
          [ 42,  43,  44]],

         [[ 45,  46,  47],
          [ 48,  49,  50],
          [ 51,  52,  53],
          [ 54,  55,  56],
          [ 57,  58,  59]]],


        [[[ 60,  61,  62],
          [ 63,  64,  65],
          [ 66,  67,  68],
          [ 69,  70,  71],
          [ 72,  73,  74]],

         [[ 75,  76,  77],
          [ 78,  79,  80],
          [ 81,  82,  83],
          [ 84,  85,  86],
          [ 87,  88,  89]],

         [[ 90,  91,  92],
          [ 93,  94,  95],
          [ 96,  97,  98],
          [ 99, 100, 101],
          [102, 103, 104]],

         [[105, 106, 107],
          [1

In [21]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.sqrt(arr)

array([0. , 1. , 1.41421356, 1.73205081, 2. ,
 2.23606798, 2.44948974, 2.64575131, 2.82842712, 3. ])