In [1]:
import tensorflow as tf

In [2]:
print(f"wersja TensorFlow: {tf.__version__}")

wersja TensorFlow: 2.10.1


In [3]:
mnist = tf.keras.datasets.mnist

(x_train,y_train), (x_test,y_test) = mnist.load_data()
x_train,x_test = x_train/255.0, x_test/255.0

11490434/11490434 [==============================] - 1s 0us/step


In [4]:
x_train.shape

(60000, 28, 28)

In [5]:
x_test.shape

(10000, 28, 28)

In [6]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [7]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.37007225, 0.5554334 , -0.3087131 , 0.6233445 , -0.26918182,
 -0.9455342 , 0.02202572, -0.19532743, -0.10459817, -0.19849822]],
 dtype=float32)

In [8]:
tf.nn.softmax(predictions).numpy()

array([[0.07083298, 0.17872179, 0.07531534, 0.1912806 , 0.07835229,
 0.03983966, 0.10483866, 0.08435799, 0.09236968, 0.08409093]],
 dtype=float32)

In [9]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [10]:
loss_fn(y_train[:1],predictions).numpy()

3.2228923

In [11]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [12]:
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2935 - accuracy: 0.9144
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1437 - accuracy: 0.9576
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1088 - accuracy: 0.9680
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0894 - accuracy: 0.9721
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0759 - accuracy: 0.9762


In [13]:
model.evaluate(x_test,y_test,verbose=2)

313/313 - 1s - loss: 0.0778 - accuracy: 0.9768 - 586ms/epoch - 2ms/step


[0.07779750227928162, 0.9768000245094299]

In [14]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [15]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[6.2261840e-09, 4.3596962e-09, 2.8705667e-06, 9.3460672e-05,
        8.5827430e-12, 1.5873053e-07, 5.4774897e-13, 9.9990129e-01,
        9.3818358e-08, 2.1370481e-06],
       [3.3789021e-08, 3.7107186e-04, 9.9961555e-01, 1.1658241e-05,
        1.1619039e-14, 1.3025202e-06, 1.8989494e-08, 8.1504282e-12,
        3.4329258e-07, 2.0124189e-12],
       [1.2790412e-06, 9.9771947e-01, 1.7315101e-04, 8.3466788e-05,
        8.2624749e-05, 2.6757236e-05, 1.5951312e-04, 8.5323711e-04,
        8.9066819e-04, 9.7837456e-06],
       [9.9991024e-01, 6.3860961e-09, 3.4197215e-05, 1.1050134e-07,
        5.6672533e-08, 1.0698255e-05, 7.6401366e-06, 3.2934218e-05,
        1.2004901e-07, 4.0048271e-06],
       [1.2054035e-06, 2.6618729e-09, 2.0717439e-06, 6.4488454e-08,
        9.9927562e-01, 4.5119762e-07, 2.5868487e-06, 3.7700847e-05,
        3.1469231e-06, 6.7718810e-04]], dtype=float32)>